### ISSUE TITLE
Move from doubles to floats

### ISSUE THREAD

**Issue by lmccalman** [NICTA/stateline#85]
we don't need doubles... we're not solving stiff DE systems =P

**Comment by sjhardy** [comment]
Well, floats are smaller so lower network overhead, but not any faster, except on GPUs/SSE2/ etc. Given that the target for stateline is complicated and hard to evaluate posteriors, does this really need to be changed?

If it does change internally, can it be hidden from the client?


On 18 Jan 2016, at 11:41 am, Lachlan McCalman <notifications@github.com<mailto:notifications@github.com>> wrote:


we don't need doubles... we're not solving stiff DE systems =P

—
Reply to this email directly or view it on GitHub<https://github.com/NICTA/stateline/issues/85>.


________________________________

The information in this e-mail may be confidential and subject to legal professional privilege and/or copyright. National ICT Australia Limited accepts no liability for any damage caused by this email or its attachments.

**Comment by lmccalman** [comment]
Yeah good point. Although stateline isn't solving stiff DEs, the forward models might be!! I'll close this for now. I'll re-phrase my issue to apply only to the adaption system, not the chains themselves. This won't affect the precision of the mcmc.
